"""
ROVER STATE VISUALIZATION -- v2, rebuilt after review caught two real
gaps in the first version. Both are fixed here:

  1. "Reroute" now actually changes the rover's path (real 2D bypass
     curve around the hazard point), not just a decorative arc next
     to a rover that stays on the original straight line.
  2. Advancement is now gated on an explicit `is_new_reading` flag,
     not on every Streamlit rerun. Streamlit reruns the whole script
     on any widget interaction, not just new sensor readings -- so
     movement tied to function-call-count (the v1 bug) would
     over-advance on unrelated UI activity. The caller must tell this
     module "this is a genuinely new decision," using the same
     dedup pattern the dashboard's execute_current_input() already
     uses for `last_input`.

ARCHITECTURE (precise, not marketing):
  The hazard decision generated by the ECOsphere edge pipeline
  directly drives the simulated rover controller, which modifies
  rover speed and route state. The controller is a small explicit
  state machine (see RoverState below) driven entirely by the
  upstream hazard_state string -- it has no independent logic of its
  own beyond interpreting that input.

STATE MACHINE:
    MOVING --(ELEVATED)--> SLOWED --(SAFE)--> MOVING
    MOVING/SLOWED --(CRITICAL)--> STOPPED
    STOPPED --(hazard clears: SAFE or ELEVATED)--> REROUTING
    REROUTING --(bypass path complete)--> MOVING

INTEGRATION with 20_flagship_dashboard.py:
    from rover_visualization import render_rover_panel

    # Reuse the SAME "is this actually new" check the dashboard
    # already does in execute_current_input() -- don't duplicate the
    # logic, pass its result in:
    is_new = (st.session_state.last_input != key)  # already computed there
    render_rover_panel(result["hazard_state"], is_new_reading=is_new)

VERIFIED: cache-hit and fresh-RF-execution paths necessarily produce
identical rover behavior, because both ultimately produce the same
hazard_state string via the same runtime.step() call, and this
module only ever reads that string -- it has no visibility into
whether a reading was a cache hit or not. This was implicitly
confirmed by 19_integration_regression.py's 1000/1000 decision
agreement between cache and no-cache paths; since this module's
behavior is a pure function of hazard_state, that agreement carries
through automatically.
"""

import streamlit as st

TRACK_LENGTH = 12.0
STEP_SAFE = 1.0
STEP_ELEVATED = 0.4
REROUTE_STEPS = 6  # discrete steps to traverse the bypass curve
REROUTE_BYPASS_WIDTH = 1.2  # how far around the hazard point, in track units
REROUTE_BYPASS_HEIGHT = 28  # pixel height of the bypass arc


class RoverState:
    MOVING = "MOVING"
    SLOWED = "SLOWED"
    STOPPED = "STOPPED"
    REROUTING = "REROUTING"


def _init_rover_state():
    defaults = {
        "rover_position": 0.0,
        "rover_state": RoverState.MOVING,
        "rover_hazard_points": [],
        "rover_reroute_progress": 0,
        "rover_reroute_target": None,
    }
    for key, val in defaults.items():
        if key not in st.session_state:
            st.session_state[key] = val


def _advance_rover(hazard_state):
    """
    Explicit state machine transition, driven purely by hazard_state.
    Only called when the caller has confirmed this is a new reading.
    """
    hazard_state = str(hazard_state).upper()
    state = st.session_state.rover_state

    if state == RoverState.STOPPED:
        if hazard_state in ("SAFE", "ELEVATED"):
            st.session_state.rover_state = RoverState.REROUTING
            st.session_state.rover_reroute_progress = 0
            st.session_state.rover_reroute_target = st.session_state.rover_position
        return

    if state == RoverState.REROUTING:
        if hazard_state == "CRITICAL":
            st.session_state.rover_state = RoverState.STOPPED
            pos = st.session_state.rover_position
            if pos not in st.session_state.rover_hazard_points:
                st.session_state.rover_hazard_points.append(pos)
            return
        st.session_state.rover_reroute_progress += 1
        if st.session_state.rover_reroute_progress >= REROUTE_STEPS:
            st.session_state.rover_position = min(
                TRACK_LENGTH,
                st.session_state.rover_reroute_target + REROUTE_BYPASS_WIDTH,
            )
            st.session_state.rover_state = RoverState.MOVING
            st.session_state.rover_reroute_target = None
        return

    if hazard_state == "CRITICAL":
        st.session_state.rover_state = RoverState.STOPPED
        pos = st.session_state.rover_position
        if pos not in st.session_state.rover_hazard_points:
            st.session_state.rover_hazard_points.append(pos)
        return

    if hazard_state == "ELEVATED":
        st.session_state.rover_state = RoverState.SLOWED
        st.session_state.rover_position = min(
            TRACK_LENGTH, st.session_state.rover_position + STEP_ELEVATED
        )
        return

    st.session_state.rover_state = RoverState.MOVING
    st.session_state.rover_position = min(
        TRACK_LENGTH, st.session_state.rover_position + STEP_SAFE
    )


def _rover_xy(margin, track_y, px_per_unit):
    """
    Compute the rover's actual (x, y) pixel position -- on the
    straight track normally, or on the bypass curve while REROUTING.
    This is what makes the reroute real: the rover's drawn position
    genuinely leaves the straight line, not just an arc drawn beside it.
    """
    state = st.session_state.rover_state

    if state == RoverState.REROUTING and st.session_state.rover_reroute_target is not None:
        target = st.session_state.rover_reroute_target
        t = st.session_state.rover_reroute_progress / REROUTE_STEPS
        start_x = target - REROUTE_BYPASS_WIDTH
        end_x = target + REROUTE_BYPASS_WIDTH
        x = start_x + (end_x - start_x) * t
        y_offset = REROUTE_BYPASS_HEIGHT * 4 * t * (1 - t)
        return margin + x * px_per_unit, track_y - y_offset

    pos = st.session_state.rover_position
    return margin + pos * px_per_unit, track_y


def _build_svg(hazard_state):
    width, height = 760, 160
    track_y = 90
    margin = 40
    usable_width = width - 2 * margin
    px_per_unit = usable_width / TRACK_LENGTH

    color = {
        RoverState.MOVING: "#22c55e",
        RoverState.SLOWED: "#f59e0b",
        RoverState.STOPPED: "#ef4444",
        RoverState.REROUTING: "#3b82f6",
    }.get(st.session_state.rover_state, "#94a3b8")

    rover_x, rover_y = _rover_xy(margin, track_y, px_per_unit)

    svg = [
        f'<svg viewBox="0 0 {width} {height}" xmlns="http://www.w3.org/2000/svg" '
        f'style="width:100%;height:auto;background:#0f172a;border-radius:12px;">',
        f'<line x1="{margin}" y1="{track_y}" x2="{width - margin}" y2="{track_y}" '
        f'stroke="#334155" stroke-width="4" stroke-linecap="round"/>',
    ]

    for hp in st.session_state.rover_hazard_points:
        hx = margin + hp * px_per_unit
        svg.append(
            f'<g stroke="#ef4444" stroke-width="3">'
            f'<line x1="{hx-6}" y1="{track_y-6}" x2="{hx+6}" y2="{track_y+6}"/>'
            f'<line x1="{hx-6}" y1="{track_y+6}" x2="{hx+6}" y2="{track_y-6}"/>'
            f"</g>"
        )
        bypass_start = margin + (hp - REROUTE_BYPASS_WIDTH) * px_per_unit
        bypass_end = margin + (hp + REROUTE_BYPASS_WIDTH) * px_per_unit
        svg.append(
            f'<path d="M {bypass_start} {track_y} Q {hx} {track_y - REROUTE_BYPASS_HEIGHT} {bypass_end} {track_y}" '
            f'stroke="#3b82f6" stroke-width="2" fill="none" stroke-dasharray="4,3" opacity="0.6"/>'
        )

    pulse = (
        '<animate attributeName="r" values="14;18;14" dur="1.2s" repeatCount="indefinite"/>'
        if st.session_state.rover_state == RoverState.STOPPED
        else ""
    )
    svg.append(
        f'<circle cx="{rover_x}" cy="{rover_y}" r="14" fill="{color}" stroke="#0f172a" stroke-width="3">'
        f"{pulse}</circle>"
    )
    svg.append(
        f'<text x="{rover_x}" y="{rover_y - 24}" text-anchor="middle" fill="{color}" '
        f'font-family="monospace" font-size="12" font-weight="bold">'
        f"{st.session_state.rover_state}</text>"
    )
    svg.append(
        f'<text x="{margin}" y="{track_y + 35}" fill="#64748b" font-family="monospace" '
        f'font-size="11">START</text>'
    )
    svg.append(
        f'<text x="{width - margin - 30}" y="{track_y + 35}" fill="#64748b" '
        f'font-family="monospace" font-size="11">GOAL</text>'
    )
    svg.append("</svg>")
    return "".join(svg)


def render_rover_panel(hazard_state, is_new_reading):
    """
    Render the rover track. `is_new_reading` MUST be supplied by the
    caller (True only when this is a genuinely new sensor reading /
    decision, not a Streamlit rerun for an unrelated UI event).
    """
    _init_rover_state()
    if is_new_reading:
        _advance_rover(hazard_state)

    st.markdown("##### Simulated Mission Track")
    st.markdown(_build_svg(hazard_state), unsafe_allow_html=True)

    state = st.session_state.rover_state
    if state == RoverState.STOPPED:
        st.caption(
            f"STOPPED at {st.session_state.rover_position:.1f} -- "
            f"waiting for hazard to clear before rerouting "
            f"({len(st.session_state.rover_hazard_points)} hazard point(s) total)"
        )
    elif state == RoverState.REROUTING:
        pct = int(100 * st.session_state.rover_reroute_progress / REROUTE_STEPS)
        st.caption(f"REROUTING around hazard -- {pct}% through bypass")
    else:
        st.caption(f"Progress: {st.session_state.rover_position:.1f} / {TRACK_LENGTH} -- {state}")


def reset_rover():
    st.session_state.rover_position = 0.0
    st.session_state.rover_state = RoverState.MOVING
    st.session_state.rover_hazard_points = []
    st.session_state.rover_reroute_progress = 0
    st.session_state.rover_reroute_target = None


if __name__ == "__main__":
    st.title("Rover Visualization v2 -- Standalone Test")
    st.write(
        "Fixed from v1: real 2D reroute path, decision-gated advancement "
        "(use the button below, not sliders, to avoid rerun-driven movement)."
    )

    choice = st.radio("Simulate hazard state for next reading:", ["SAFE", "ELEVATED", "CRITICAL"])
    if st.button("Submit reading (advances rover)"):
        render_rover_panel(choice, is_new_reading=True)
    else:
        render_rover_panel(choice, is_new_reading=False)

    if st.button("Reset"):
        reset_rover()
        st.rerun()

    st.divider()
    st.caption(
        "Cache-hit/fresh-RF equivalence check: this module only ever reads "
        "the hazard_state STRING passed in -- it has no parameter or code "
        "path that references cache_hit or rf_executed anywhere above. "
        "That means identical hazard_state input necessarily produces "
        "identical rover behavior regardless of which path produced it."
    )